products = [
    {
        "_id" : "1",
        "image": "/resources/img/1.jpg",
        "name": "Denim Jeans",
        "description": "comfortable wear and durable.",
        "category": "man",
        "size": ["S", "M", "L"],
        "price": "3500",
        "countInStock": "12",
    },
    {
        "_id" : "2",
        "image": "/resources/img/2.jpg",
        "name": "Formal Shirt",
        "description": "For official use. Very comfortable wear and durable.",
        "category": "man",
        "size": ["S", "M", "L"],
        "price": "2500",
        "countInStock": "4",
    },
    {
        "_id" : "3",
        "image": "/resources/img/3.jpg",
        "name": "One Piece",
        "description": "Very fashinable, slim fit with great fabric.",
        "category": "women",
        "size": ["S", "M", "L"],
        "price": "4500",
        "countInStock": "6",
    },
    {
        "_id" : "4",
        "image": "/resources/img/4.jpg",
        "name": "T-Shirt",
        "description": "summer use. temporary description. will update later.",
        "category": "man",
        "size": ["S", "M", "L"],
        "price": "500",
        "countInStock": "12",
    },
    {
        "_id" : "5",
        "image": "/resources/img/5.jpg",
        "name": "Sweater",
        "description": "Indoor and outdoor wear for winter. Made from 100% organic metarials.",
        "category": "women",
        "size": ["S", "M", "L"],
        "price": "2800",
        "countInStock": "8",
    },
    {
        "_id" : "6",
        "image": "/resources/img/6.jpg",
        "name": "Formal shirt for Women",
        "description": "Very fashinable, slim fit with great fabric.",
        "category": "women",
        "size": ["S", "M", "L"],
        "price": "1900",
        "countInStock": "8",
    },
]
